# Generated by Django 3.2.6 on 2021-08-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinematicket_apps_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
