# Generated by Django 3.2.6 on 2021-08-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Required. 20 letters or fewer', max_length=20)),
                ('last_name', models.CharField(help_text='Required. 20 letters or fewer', max_length=20)),
                ('user_id', models.UUIDField(help_text='Required. Must be 36 characters')),
                ('phone', models.CharField(error_messages={'unique': 'A user with that phone number already exists.'}, help_text='Required. Must be 11 numbers', max_length=11)),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, help_text='Required. Valid email address of 30 letters or fewer', max_length=30, unique=True)),
                ('password', models.CharField(help_text='Required. Valid password must be 8 characters or more', max_length=100)),
                ('dob', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Inactive', 'Inactive')], error_messages={'invalid_choice': 'Invalid choice'}, max_length=10)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
